# need super user privileges to execute the following commands
language: generic
sudo: required
services:
        - docker

before_install:        
        - docker build -t alexbr9007/docker-kubernetes-udemy/docker-react -f Dockerfile.dev .

script:
        - docker run alexbr9007/docker-kubernetes-udemy/docker-react npm run test -- --coverage


        

